### ISSUE TITLE
Tutorial Needed

### ISSUE THREAD

**Issue by ashkan-software** [anrlutdallas/anrlutdallas.github.io#11]
A basic tutorial is needed to do simple things, like how to make a personal page, (which is basically the email you sent out to everyone to copy my source code) or how to make a URL work in Preview here

**Comment by ashkan-software** [comment]
maybe can be added after adding gallery, news and announcements, and fixing publication

**Comment by caleb-fung** [comment]
Add to wiki
- Basic html, css
- Updating events
- Team member page
- Publication
- Resources
- Gallery
- Others: links

**Comment by caleb-fung** [comment]
Max news and announcements combined should not be over 5.

**Comment by ashkan-software** [comment]
To post pictures in the Flickr gallery
1- Use the credentials provided on our slack channel #management to log in to flickr.com
2- Click on the upload button (cloud icon)
3- Browse the pictures from the event (only pictures from one event; if you have multiple events, you need to make multiple albums)
4- Select all the pictures in the Flickr dashboard, and then click the "Add to albums" button 
5- You will be asked to enter title of the album. Name the album
6- You will be asked to enter description of the album. add the description of the album (e.g. date, location, purpose, etc.)
7- Click done, and then click "Upload"

**Comment by ashkan-software** [comment]
All the tutorials added and edited!
