### ISSUE TITLE
[urgent] Fix publications page, conference names, numbering

### ISSUE THREAD

**Issue by ashkan-software** [anrlutdallas/anrlutdallas.github.io#12]
Please run your scraper again so that you get the conference year along with the conference name (like "Globecom 2016", instead of "Globecom")

I think we need to remove the "number", since if we don't, every time some one needs to adda paper to the top of the table, they need to update all the rows. Or, you can simply do the numbering from bottom to up (so the latest paper simply gets the biggest number, no update is needed)

**Comment by caleb-fung** [comment]
@ashkan-software I have updated the table structure (the header and html formatting). I'm not sure how you want to number the rows. I can do it with Javascript.
